import { Fragment } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Fragment>
      {children}
    </Fragment>
  )
}
