version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
      - ./app/shared:/app/shared:rw
    networks:
      - transcendance-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/backend:/app
      - /app/node_modules
      - ./app/shared:/app/shared:rw
    networks:
      - transcendance-network
    ports:
      - "4000:4000"
      - "5555:5555"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - transcendance-network

volumes:
  pgdata:

networks:
  transcendance-network:
