import MyHeader from "@/components/organism/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-500 to-fuchsia-500 h-[100vh]">
        <MyHeader display={true}/>
        {children}
      </body>
    </html>
  )
}
