'use client'

import MyHeader from "@/components/organism/Header"

const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function getPathname() {
  console.log(window.location.pathname)
  if (window.location.pathname === "/")
    return false
  return true
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  // const displayHeader : boolean = getPathname();
  // console.log(displayHeader)

  return (
      <html lang="en">
        <body className="bg-gradient-to-r from-indigo-500 to-fuchsia-500 h-[100vh]">
          {children}
        </body>
      </html>
  )
}
