import type { Metadata } from 'next'
import './globals.css'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <h1 className={`{press_Start_2P.className}`}>{children}</h1> */}
      {/* <body> className={quantico.className}{children}</body> */}
      <body>{children}</body>
    </html>
  )
}
